development:
<<: *default
  database: Smart_saver
  username: monnie
  password: monnie
  adapter: postgresql

test:
<<: *default
  adapter: postgresql
  encoding: unicode
  database: Smart_save tests
  pool: 5
  username: monnie
  password: monnie
  port: 5432

  production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
