default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Smart_saver
  username: monnie
  password: monnie

test:
  <<: *default
  database: Smart_save_tests
  username: monnie
  password: monnie

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>